/**
 * AegisScan scan-template catalog.
 *
 * Every Nessus/Tenable scan type is represented here. Each template declares an
 * honest execution mode so the console never claims to run a check it cannot:
 *
 *  - native   → executed server-side by the built-in HTTP/TLS engine
 *  - agent    → requires an external scan agent (raw sockets, credentials,
 *               local host access); results arrive through /api/public/agent/ingest
 *  - analysis → evaluated against data already in the platform
 */

export type ScanMode = "native" | "agent" | "analysis";

export type ScanCategory =
  | "Discovery"
  | "Network"
  | "Web & API"
  | "Endpoint & OS"
  | "Infrastructure"
  | "Cloud & Container"
  | "Compliance"
  | "Specialized"
  | "Continuous";

export interface ScanTemplate {
  id: string;
  name: string;
  category: ScanCategory;
  mode: ScanMode;
  /** Short one-liner used in pickers and cards. */
  description: string;
  purpose: string;
  techniques: string[];
  detects: string[];
  /** Engine plugin families executed for native templates. */
  families: string[];
  credentials?: string[];
  /** Job type an external agent receives for agent-mode templates. */
  agentJob?: string;
  /** Compliance framework key for analysis-mode compliance templates. */
  framework?: string;
}

const t = (x: ScanTemplate): ScanTemplate => x;

export const SCAN_CATALOG: ScanTemplate[] = [
  /* ------------------------------- Discovery ------------------------------- */
  t({
    id: "host_discovery",
    name: "Host Discovery",
    category: "Discovery",
    mode: "agent",
    description: "Finds every live device on a network before deeper assessment.",
    purpose: "Enumerate live hosts, MAC addresses, hostnames and IPs across a subnet.",
    techniques: [
      "ARP sweep",
      "ICMP echo",
      "TCP SYN ping",
      "TCP ACK ping",
      "UDP probes",
      "Reverse DNS",
    ],
    detects: ["Live hosts", "MAC addresses", "Hostnames", "IP addresses", "Responsive ports"],
    families: [],
    agentJob: "host_discovery",
  }),
  t({
    id: "external_attack_surface",
    name: "External Attack Surface Scan",
    category: "Discovery",
    mode: "native",
    description: "Maps internet-facing exposure: reachable services, panels and leaked paths.",
    purpose: "Understand what an unauthenticated attacker sees from the public internet.",
    techniques: [
      "HTTP/HTTPS probing",
      "Redirect chain analysis",
      "Path enumeration",
      "Banner extraction",
    ],
    detects: [
      "Internet-facing services",
      "Exposed admin panels",
      "Debug endpoints",
      "Sensitive files",
    ],
    families: ["fingerprint", "exposure", "headers", "tls", "device"],
  }),
  t({
    id: "internal_network_scan",
    name: "Internal Network Scan",
    category: "Discovery",
    mode: "agent",
    description: "Credentialed sweep of internal assets from inside the perimeter.",
    purpose: "Assess internal hosts with credentials for deep, low-false-positive results.",
    techniques: [
      "SYN/UDP port sweeps",
      "Service identification",
      "OS fingerprinting",
      "Credentialed local checks",
    ],
    detects: [
      "Internal services",
      "Missing patches",
      "Weak configuration",
      "Lateral movement paths",
    ],
    families: [],
    credentials: ["SSH", "SMB", "WinRM"],
    agentJob: "internal_network_scan",
  }),

  /* -------------------------------- Network -------------------------------- */
  t({
    id: "basic_network_scan",
    name: "Basic Network Scan",
    category: "Network",
    mode: "native",
    description: "The default comprehensive assessment with full all-ports sweep across every service and web-reachable plugin family.",
    purpose:
      "Broad vulnerability assessment: all-ports discovery, listening services, versions, misconfiguration and CVE correlation.",
    techniques: [
      "All-ports network sweep & service detection",
      "Banner grabbing & service identification",
      "Version fingerprinting",
      "Database & remote service exposure audit",
      "CVE correlation",
    ],
    detects: [
      "Open network ports & services",
      "CVEs",
      "Running services",
      "Exposed infrastructure/databases",
      "Risk score",
      "Exploitable vulnerabilities",
    ],
    families: [
      "ports",
      "database",
      "fingerprint",
      "headers",
      "tls",
      "exposure",
      "webapp",
      "api",
      "device",
      "cve",
    ],
  }),
  t({
    id: "advanced_scan",
    name: "Advanced Scan",
    category: "Network",
    mode: "native",
    description: "Every plugin family enabled — all-ports sweep, deep crawl and aggressive correlation for maximum coverage.",
    purpose: "Full-customisation enterprise scan with all families, extended port sweeps, deep paths and CVE matching.",
    techniques: [
      "All-ports sweep & service detection",
      "All plugin families",
      "Extended path list",
      "Deep crawl",
      "Aggressive correlation",
    ],
    detects: ["All open ports, services and everything the engine can observe over HTTP/TLS/DNS/sockets"],
    families: [
      "ports",
      "database",
      "cloud",
      "container",
      "endpoint",
      "fingerprint",
      "headers",
      "tls",
      "exposure",
      "webapp",
      "api",
      "dns",
      "mail",
      "cve_hunt",
      "device",
      "cve",
    ],
  }),
  t({
    id: "quick_scan",
    name: "Quick Assessment",
    category: "Network",
    mode: "native",
    description: "Fast pass over the highest-signal checks. Good for continuous monitoring.",
    purpose: "Low-cost recurring check on critical assets.",
    techniques: ["Fingerprinting", "Header audit", "TLS audit"],
    detects: ["Transport weaknesses", "Missing security headers", "Technology drift"],
    families: ["fingerprint", "headers", "tls"],
  }),
  t({
    id: "dns_audit",
    name: "DNS Security Audit",
    category: "Network",
    mode: "native",
    description: "DNSSEC, record hygiene, dangling records and resolver exposure.",
    purpose: "Validate DNS configuration and find takeover-prone records.",
    techniques: [
      "DNS-over-HTTPS queries",
      "DNSSEC validation",
      "CNAME chain analysis",
      "Record inventory",
    ],
    detects: ["Missing DNSSEC", "Dangling CNAMEs", "Wildcards", "Missing CAA", "Zone info leakage"],
    families: ["dns"],
  }),
  t({
    id: "mail_security",
    name: "Email Server Security",
    category: "Network",
    mode: "native",
    description: "SPF, DKIM policy, DMARC enforcement and MX transport posture.",
    purpose: "Prevent spoofing and confirm mail transport security policy.",
    techniques: ["SPF/DMARC record lookup", "MX enumeration", "Policy strictness analysis"],
    detects: ["Missing SPF", "Permissive ~all/+all", "Missing or p=none DMARC", "No MX hardening"],
    families: ["mail"],
  }),
  t({
    id: "snmp_audit",
    name: "SNMP Audit",
    category: "Network",
    mode: "agent",
    description: "Community strings, protocol version and device configuration exposure.",
    purpose: "Find SNMP devices answering with default or guessable community strings.",
    techniques: ["SNMP v1/v2c/v3 probes", "Community string bruteforce", "MIB walk"],
    detects: [
      "public/private community strings",
      "SNMPv1/v2c in use",
      "Device configuration leakage",
    ],
    families: [],
    agentJob: "snmp_audit",
  }),
  t({
    id: "ftp_security",
    name: "FTP Security Scan",
    category: "Network",
    mode: "agent",
    description: "Anonymous login, cleartext credentials and weak FTP authentication.",
    purpose: "Identify insecure file transfer services.",
    techniques: ["FTP banner grab", "Anonymous login attempt", "AUTH TLS negotiation"],
    detects: [
      "Anonymous access",
      "Cleartext credentials",
      "Writable directories",
      "Outdated daemons",
    ],
    families: [],
    agentJob: "ftp_security",
  }),
  t({
    id: "ssh_security",
    name: "SSH Security Scan",
    category: "Network",
    mode: "agent",
    description: "Cipher suites, key exchange, root login and deprecated algorithms.",
    purpose: "Harden SSH endpoints against downgrade and credential attacks.",
    techniques: ["SSH banner grab", "Algorithm negotiation", "sshd_config review (credentialed)"],
    detects: ["Weak ciphers/MACs", "Weak KEX", "PermitRootLogin yes", "Password authentication"],
    families: [],
    credentials: ["SSH"],
    agentJob: "ssh_security",
  }),
  t({
    id: "smb_vuln",
    name: "SMB Vulnerability Scan",
    category: "Network",
    mode: "agent",
    description: "SMB signing, SMBv1, shares, anonymous login and NTLM weaknesses.",
    purpose: "Eliminate the most abused Windows lateral-movement surface.",
    techniques: ["SMB dialect negotiation", "Null session attempt", "Share enumeration"],
    detects: ["SMBv1 enabled", "Signing not required", "Anonymous shares", "NTLMv1 fallback"],
    families: [],
    agentJob: "smb_vuln",
  }),
  t({
    id: "wireless_scan",
    name: "Wireless Network Scan",
    category: "Network",
    mode: "agent",
    description: "Wi-Fi encryption strength, rogue APs and weak authentication.",
    purpose: "Detect insecure or unauthorised wireless infrastructure.",
    techniques: ["802.11 monitor-mode capture", "Beacon analysis", "BSSID inventory"],
    detects: ["WEP/WPA-TKIP", "Open networks", "Rogue access points", "Weak EAP configuration"],
    families: [],
    agentJob: "wireless_scan",
  }),
  t({
    id: "iot_scan",
    name: "IoT Device Scan",
    category: "Network",
    mode: "native",
    description: "Fingerprints cameras, printers, routers and embedded web consoles.",
    purpose: "Identify embedded devices exposing management interfaces.",
    techniques: ["Embedded HTTP fingerprinting", "Default-page matching", "Realm/banner analysis"],
    detects: ["Cameras", "Printers", "Routers", "Smart devices", "Default credential portals"],
    families: ["device", "fingerprint", "headers"],
  }),

  /* ------------------------------- Web & API -------------------------------- */
  t({
    id: "web_audit",
    name: "Web Application Tests",
    category: "Web & API",
    mode: "native",
    description:
      "Full HTTP crawl: fingerprinting, headers, cookies, exposure paths, OWASP probes, CVE correlation.",
    purpose: "OWASP-aligned assessment of a web application.",
    techniques: [
      "Crawling",
      "Reflection probes",
      "Redirect testing",
      "Cookie analysis",
      "Error-message analysis",
    ],
    detects: [
      "Reflected XSS",
      "Open redirect",
      "Directory traversal indicators",
      "Insecure cookies",
      "Information disclosure",
      "Authentication/session weaknesses",
    ],
    families: ["fingerprint", "headers", "exposure", "webapp", "tls", "cve"],
  }),
  t({
    id: "api_audit",
    name: "API Security Scan",
    category: "Web & API",
    mode: "native",
    description:
      "OpenAPI/Swagger discovery, unauthenticated endpoint enumeration, GraphQL introspection, CORS.",
    purpose: "Test REST and GraphQL surfaces for exposure and broken authorization.",
    techniques: ["Spec discovery", "Endpoint enumeration", "GraphQL introspection", "CORS probing"],
    detects: [
      "Unauthenticated endpoints",
      "Exposed API schema",
      "Broken object-level authorization indicators",
      "Verbose errors",
      "Missing rate limiting signals",
    ],
    families: ["api", "headers", "fingerprint"],
  }),
  t({
    id: "tls_audit",
    name: "SSL/TLS Scan",
    category: "Web & API",
    mode: "native",
    description:
      "HTTPS enforcement, certificate chain, HSTS, mixed content and transport weaknesses.",
    purpose: "Validate transport security end to end.",
    techniques: ["TLS handshake analysis", "Certificate inspection", "Redirect hygiene checks"],
    detects: [
      "Expired certificates",
      "Hostname mismatch",
      "Self-signed chains",
      "Weak protocol/cipher signals",
      "No HSTS",
    ],
    families: ["tls", "headers"],
  }),
  t({
    id: "exposure_audit",
    name: "Exposure & Attack Surface",
    category: "Web & API",
    mode: "native",
    description: "Sensitive file, backup, VCS metadata, admin panel and debug endpoint discovery.",
    purpose: "Find data and interfaces that should never be public.",
    techniques: ["Path enumeration", "Content signature matching", "Directory listing detection"],
    detects: ["/.env", "/.git/config", "Backups and dumps", "Directory listings", "Admin panels"],
    families: ["exposure", "fingerprint"],
  }),

  /* ---------------------------- Endpoint & OS ------------------------------- */
  t({
    id: "credentialed_patch_audit",
    name: "Credentialed Patch Audit",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Logs in over SSH/SMB/WinRM to verify installed and missing patches.",
    purpose: "Patch-level accuracy far beyond banner inference.",
    techniques: ["SSH/SMB/WinRM login", "Package manager query", "KB/update enumeration"],
    detects: ["Missing patches", "KB gaps", "Outdated packages", "End-of-life components"],
    families: [],
    credentials: ["SSH", "SMB", "WinRM"],
    agentJob: "credentialed_patch_audit",
  }),
  t({
    id: "offline_config_audit",
    name: "Offline Configuration Audit",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Audits exported configuration files without touching a live system.",
    purpose: "Review device and OS configuration where live access is not permitted.",
    techniques: ["Config file parsing", "Policy rule evaluation"],
    detects: ["Windows policy gaps", "Insecure Linux configuration", "Weak network device configs"],
    families: [],
    agentJob: "offline_config_audit",
  }),
  t({
    id: "malware_scan",
    name: "Malware Scan",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Known malware artifacts, backdoors, rootkits and persistence mechanisms.",
    purpose: "Detect compromise indicators on managed endpoints.",
    techniques: [
      "File hash matching",
      "Service and task enumeration",
      "Registry inspection",
      "YARA rules",
    ],
    detects: [
      "Malicious binaries",
      "Suspicious services",
      "Malicious registry keys",
      "Rootkits",
      "Persistence",
    ],
    families: [],
    credentials: ["SSH", "SMB"],
    agentJob: "malware_scan",
  }),
  t({
    id: "mobile_scan",
    name: "Mobile Device Scan",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Android and iOS posture through MDM data collection.",
    purpose: "Assess mobile fleet compliance and integrity.",
    techniques: ["MDM API collection", "Device attestation review"],
    detects: ["Jailbreak/root", "Weak passcode policy", "Missing OS updates", "Unmanaged apps"],
    families: [],
    agentJob: "mobile_scan",
  }),
  t({
    id: "windows_audit",
    name: "Windows Security Audit",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Registry, services, policies, firewall, Defender and update state.",
    purpose: "Full Windows host hardening review.",
    techniques: ["WMI/WinRM queries", "Registry read", "Policy export"],
    detects: [
      "Insecure policies",
      "Disabled firewall/Defender",
      "Risky services",
      "Missing updates",
    ],
    families: [],
    credentials: ["SMB", "WinRM"],
    agentJob: "windows_audit",
  }),
  t({
    id: "linux_audit",
    name: "Linux Security Audit",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Packages, permissions, SELinux/AppArmor, SSH, cron and services.",
    purpose: "Full Linux host hardening review.",
    techniques: ["SSH command execution", "Package manifest read", "File permission audit"],
    detects: ["Vulnerable packages", "World-writable paths", "MAC disabled", "Risky cron jobs"],
    families: [],
    credentials: ["SSH"],
    agentJob: "linux_audit",
  }),
  t({
    id: "macos_audit",
    name: "macOS Security Audit",
    category: "Endpoint & OS",
    mode: "agent",
    description: "System settings, firewall, Gatekeeper, FileVault and software updates.",
    purpose: "Assess macOS endpoint hardening.",
    techniques: ["SSH/MDM collection", "profiles and defaults read"],
    detects: ["FileVault off", "Gatekeeper disabled", "Firewall off", "Pending updates"],
    families: [],
    credentials: ["SSH"],
    agentJob: "macos_audit",
  }),
  t({
    id: "active_directory_audit",
    name: "Active Directory Audit",
    category: "Endpoint & OS",
    mode: "agent",
    description: "Privileged users, Kerberos hygiene, password policy and LDAP security.",
    purpose: "Reduce domain-wide compromise paths.",
    techniques: ["LDAP queries", "Kerberos ticket analysis", "GPO review"],
    detects: [
      "Excess Domain Admins",
      "Kerberoastable accounts",
      "Weak password policy",
      "Unsigned LDAP",
    ],
    families: [],
    credentials: ["LDAP", "SMB"],
    agentJob: "active_directory_audit",
  }),

  /* ---------------------------- Infrastructure ------------------------------ */
  t({
    id: "database_audit",
    name: "Database Auditing",
    category: "Infrastructure",
    mode: "agent",
    description: "Oracle, MySQL, PostgreSQL, SQL Server and MongoDB configuration review.",
    purpose: "Secure the data tier: accounts, encryption, patching and configuration.",
    techniques: ["Authenticated DB login", "System catalog queries", "Version comparison"],
    detects: [
      "Default accounts",
      "Weak passwords",
      "No encryption at rest/in transit",
      "Missing patches",
    ],
    families: [],
    credentials: ["Database user"],
    agentJob: "database_audit",
  }),
  t({
    id: "scada_ics",
    name: "SCADA / ICS Scan",
    category: "Infrastructure",
    mode: "agent",
    description: "Modbus, BACnet, DNP3 and PLC-safe interrogation.",
    purpose: "Assess operational technology without disrupting processes.",
    techniques: [
      "Passive protocol listening",
      "Safe read-only function codes",
      "Vendor fingerprinting",
    ],
    detects: [
      "Exposed PLCs",
      "Unauthenticated protocols",
      "Vulnerable firmware",
      "Siemens/Rockwell devices",
    ],
    families: [],
    agentJob: "scada_ics",
  }),
  t({
    id: "hypervisor_audit",
    name: "Hypervisor Security Audit",
    category: "Infrastructure",
    mode: "native",
    description: "ESXi / Hyper-V management console exposure and patch level fingerprinting.",
    purpose: "Find virtualization management planes reachable from the network.",
    techniques: ["Management console fingerprinting", "Build/version extraction", "TLS review"],
    detects: ["Exposed ESXi/vCenter UI", "Outdated builds", "Weak console TLS"],
    families: ["device", "fingerprint", "tls", "cve"],
  }),
  t({
    id: "vm_assessment",
    name: "Virtual Machine Assessment",
    category: "Infrastructure",
    mode: "agent",
    description: "Guest OS posture and virtualization-specific security controls.",
    purpose: "Assess VM guests and their isolation configuration.",
    techniques: ["Guest credentialed collection", "Hypervisor API inventory"],
    detects: [
      "Unpatched guests",
      "Snapshot sprawl",
      "Insecure guest tools",
      "Shared folder exposure",
    ],
    families: [],
    credentials: ["SSH", "WinRM", "Hypervisor API"],
    agentJob: "vm_assessment",
  }),

  /* -------------------------- Cloud & Container ----------------------------- */
  t({
    id: "container_security",
    name: "Container Security Scan",
    category: "Cloud & Container",
    mode: "agent",
    description: "Docker, Podman and OCI images: vulnerable packages, secrets, misconfiguration.",
    purpose: "Shift-left image assessment before and after deployment.",
    techniques: ["Image layer extraction", "SBOM generation", "Secret pattern scanning"],
    detects: [
      "Vulnerable OS/app packages",
      "Embedded secrets",
      "Root containers",
      "Outdated base images",
    ],
    families: [],
    agentJob: "container_security",
  }),
  t({
    id: "kubernetes_security",
    name: "Kubernetes Security",
    category: "Cloud & Container",
    mode: "agent",
    description: "RBAC, network policies, secrets, pods, API server and etcd.",
    purpose: "Harden the cluster control plane and workload posture.",
    techniques: ["Kube API inventory", "CIS Kubernetes benchmark checks", "Manifest analysis"],
    detects: [
      "Over-permissive RBAC",
      "No network policies",
      "Plaintext secrets",
      "Privileged pods",
      "Exposed etcd",
    ],
    families: [],
    credentials: ["Kubeconfig / service account"],
    agentJob: "kubernetes_security",
  }),
  t({
    id: "cloud_audit",
    name: "Cloud Infrastructure Audit",
    category: "Cloud & Container",
    mode: "agent",
    description: "AWS, Azure and GCP posture: IAM, storage, networking, encryption and logging.",
    purpose: "Continuous cloud security posture management.",
    techniques: ["Read-only cloud API collection", "Policy evaluation", "Drift comparison"],
    detects: [
      "Public buckets",
      "Over-broad IAM",
      "Open security groups",
      "Unencrypted volumes",
      "Logging disabled",
    ],
    families: [],
    credentials: ["Cloud read-only role"],
    agentJob: "cloud_audit",
  }),

  /* ------------------------------ Specialized ------------------------------- */
  t({
    id: "log4shell",
    name: "Log4Shell Detection",
    category: "Specialized",
    mode: "native",
    description: "Vulnerable Log4j versions and exploitable Java service indicators.",
    purpose: "Hunt CVE-2021-44228 / CVE-2021-45046 exposure.",
    techniques: [
      "JNDI-safe header injection markers",
      "Java stack fingerprinting",
      "Version banner matching",
    ],
    detects: ["Log4j 2.x < 2.17", "Java app servers", "JNDI-reachable request handlers"],
    families: ["cve_hunt", "fingerprint"],
  }),
  t({
    id: "shellshock",
    name: "Shellshock Detection",
    category: "Specialized",
    mode: "native",
    description: "Vulnerable Bash installations reachable through CGI.",
    purpose: "Hunt CVE-2014-6271 and its variants.",
    techniques: ["CGI path enumeration", "Crafted User-Agent function definition probe"],
    detects: ["Vulnerable Bash CGI handlers", "Legacy cgi-bin surfaces"],
    families: ["cve_hunt"],
  }),
  t({
    id: "bash_vulns",
    name: "Bash Vulnerability Scan",
    category: "Specialized",
    mode: "native",
    description: "Bash CVE family checks against reachable CGI and shell-backed endpoints.",
    purpose: "Broader Bash CVE coverage beyond the original Shellshock probe.",
    techniques: ["Variant payload probes", "Response anomaly comparison"],
    detects: ["CVE-2014-6271", "CVE-2014-7169", "CVE-2014-6277/6278"],
    families: ["cve_hunt"],
  }),
  t({
    id: "wannacry",
    name: "WannaCry Scan",
    category: "Specialized",
    mode: "agent",
    description: "SMBv1, MS17-010 and EternalBlue exposure.",
    purpose: "Confirm the classic worm surface is closed.",
    techniques: ["SMB dialect negotiation", "MS17-010 safe check"],
    detects: ["SMBv1 enabled", "MS17-010 unpatched", "EternalBlue exposure"],
    families: [],
    agentJob: "wannacry",
  }),
  t({
    id: "badlock",
    name: "Badlock Detection",
    category: "Specialized",
    mode: "agent",
    description: "Microsoft SAM/LSAD (Badlock) SMB vulnerability check.",
    purpose: "Detect CVE-2016-0128 / CVE-2016-2118 exposure.",
    techniques: ["DCERPC negotiation", "Signing policy inspection"],
    detects: ["Badlock-vulnerable SMB stacks", "Downgrade-capable RPC"],
    families: [],
    agentJob: "badlock",
  }),
  t({
    id: "ransomware",
    name: "Ransomware Detection",
    category: "Specialized",
    mode: "agent",
    description: "Common ransomware entry vectors: RDP, SMB and backup exposure.",
    purpose: "Close the paths ransomware crews actually use.",
    techniques: ["RDP exposure check", "SMB weakness check", "Backup share review"],
    detects: [
      "Internet-exposed RDP",
      "SMB weaknesses",
      "Unprotected backups",
      "KEV-listed initial access CVEs",
    ],
    families: [],
    agentJob: "ransomware",
  }),
  t({
    id: "spectre_meltdown",
    name: "Spectre / Meltdown Detection",
    category: "Specialized",
    mode: "agent",
    description: "CPU speculative-execution mitigation status.",
    purpose: "Verify microcode and OS mitigations are active.",
    techniques: ["Credentialed mitigation flag read", "Microcode version check"],
    detects: ["Disabled mitigations", "Outdated microcode", "Vulnerable kernel builds"],
    families: [],
    credentials: ["SSH", "WinRM"],
    agentJob: "spectre_meltdown",
  }),
  t({
    id: "printnightmare",
    name: "PrintNightmare Scan",
    category: "Specialized",
    mode: "agent",
    description: "Vulnerable Windows Print Spooler configuration.",
    purpose: "Detect CVE-2021-34527 exposure and unsafe spooler policy.",
    techniques: ["Spooler service state check", "Point-and-Print policy read"],
    detects: [
      "Spooler enabled on DCs",
      "NoWarningNoElevationOnInstall",
      "Unpatched spooler builds",
    ],
    families: [],
    credentials: ["SMB", "WinRM"],
    agentJob: "printnightmare",
  }),

  /* ------------------------------ Compliance -------------------------------- */
  t({
    id: "compliance_scan",
    name: "Compliance Scan",
    category: "Compliance",
    mode: "analysis",
    description: "Evaluate every framework at once against current findings and asset data.",
    purpose: "One pass/fail view across all supported benchmarks.",
    techniques: ["Control-to-finding mapping", "Asset posture evaluation"],
    detects: ["Failing controls", "Not-assessed controls", "Remediation actions"],
    families: [],
    framework: "ALL",
  }),
  t({
    id: "cis_compliance",
    name: "CIS Compliance",
    category: "Compliance",
    mode: "analysis",
    description: "Center for Internet Security benchmark controls.",
    purpose: "Measure hardening against CIS benchmarks.",
    techniques: ["Benchmark control mapping"],
    detects: ["Pass / fail / not assessed per control"],
    families: [],
    framework: "CIS",
  }),
  t({
    id: "stig_compliance",
    name: "DISA STIG Compliance",
    category: "Compliance",
    mode: "analysis",
    description: "U.S. DoD Security Technical Implementation Guide requirements.",
    purpose: "Assess STIG alignment for defense environments.",
    techniques: ["STIG control mapping"],
    detects: ["CAT I/II/III findings"],
    families: [],
    framework: "STIG",
  }),
  t({
    id: "pci_compliance",
    name: "PCI DSS Compliance",
    category: "Compliance",
    mode: "analysis",
    description: "Payment card environment security controls.",
    purpose: "Validate PCI DSS technical requirements.",
    techniques: ["Requirement mapping", "Severity gating"],
    detects: ["Failing PCI requirements", "Cardholder data exposure risks"],
    families: [],
    framework: "PCI",
  }),
  t({
    id: "hipaa_compliance",
    name: "HIPAA Compliance",
    category: "Compliance",
    mode: "analysis",
    description: "Healthcare security rule technical safeguards.",
    purpose: "Review configurations relevant to ePHI protection.",
    techniques: ["Safeguard mapping"],
    detects: ["Transmission security gaps", "Access control gaps", "Audit control gaps"],
    families: [],
    framework: "HIPAA",
  }),
  t({
    id: "iso27001_audit",
    name: "ISO 27001 Audit",
    category: "Compliance",
    mode: "analysis",
    description: "Annex A technical controls supporting ISO/IEC 27001.",
    purpose: "Evidence technical control coverage for certification.",
    techniques: ["Annex A control mapping"],
    detects: ["Uncovered technical controls"],
    families: [],
    framework: "ISO27001",
  }),
  t({
    id: "gdpr_checks",
    name: "GDPR Security Checks",
    category: "Compliance",
    mode: "analysis",
    description: "Configurations relating to protection of personal data.",
    purpose: "Support Article 32 security-of-processing obligations.",
    techniques: ["Data-exposure mapping", "Transport security evaluation"],
    detects: ["Personal data exposure paths", "Unencrypted transport", "Missing access controls"],
    families: [],
    framework: "GDPR",
  }),
  t({
    id: "nist_compliance",
    name: "NIST Compliance",
    category: "Compliance",
    mode: "analysis",
    description: "NIST CSF / 800-53 aligned technical control review.",
    purpose: "Track alignment with NIST guidance.",
    techniques: ["CSF function mapping", "800-53 control mapping"],
    detects: ["Identify/Protect/Detect gaps"],
    families: [],
    framework: "NIST",
  }),
  t({
    id: "custom_policy",
    name: "Custom Policy Scan",
    category: "Compliance",
    mode: "analysis",
    description: "Your own audit policy built from severity, family and asset predicates.",
    purpose: "Encode organisation-specific rules as pass/fail controls.",
    techniques: ["User-defined predicates", "Finding query evaluation"],
    detects: ["Violations of your own policy"],
    families: [],
    framework: "CUSTOM",
  }),

  /* ------------------------------ Continuous -------------------------------- */
  t({
    id: "agent_scan",
    name: "Agent-based Scan",
    category: "Continuous",
    mode: "agent",
    description: "Installed agents assess endpoints that are offline or off-network at scan time.",
    purpose: "Continuous collection without direct network reachability.",
    techniques: ["Local collection", "Store-and-forward ingest", "Scheduled check-in"],
    detects: ["Full local host posture", "Patch state", "Configuration drift"],
    families: [],
    agentJob: "agent_scan",
  }),
  t({
    id: "live_results",
    name: "Live Results Analysis",
    category: "Continuous",
    mode: "analysis",
    description: "Re-evaluates existing findings against new plugins and intelligence — no rescan.",
    purpose: "Reflect newly published CVE, EPSS and KEV data instantly.",
    techniques: ["Feed diffing", "Priority recomputation", "Finding re-scoring"],
    detects: ["Newly weaponised vulnerabilities", "KEV additions", "EPSS spikes"],
    families: [],
  }),
];

export const SCAN_CATEGORIES: ScanCategory[] = [
  "Discovery",
  "Network",
  "Web & API",
  "Endpoint & OS",
  "Infrastructure",
  "Cloud & Container",
  "Compliance",
  "Specialized",
  "Continuous",
];

export const MODE_LABEL: Record<ScanMode, string> = {
  native: "Runs here",
  agent: "Agent required",
  analysis: "Analysis",
};

export const MODE_CLASS: Record<ScanMode, string> = {
  native: "bg-sev-low/15 text-sev-low border-sev-low/30",
  agent: "bg-sev-medium/15 text-sev-medium border-sev-medium/30",
  analysis: "bg-primary/15 text-primary border-primary/30",
};

export function getTemplate(id: string): ScanTemplate | undefined {
  return SCAN_CATALOG.find((x) => x.id === id);
}

export const NATIVE_TEMPLATES = SCAN_CATALOG.filter((x) => x.mode === "native");

/** The stage pipeline every scan conceptually walks through. */
export const SCAN_WORKFLOW = [
  "Target selection",
  "Host discovery",
  "Port scanning",
  "Service detection",
  "OS fingerprinting",
  "Credential login",
  "Plugin execution",
  "Configuration audit",
  "Compliance checks",
  "Vulnerability correlation",
  "Risk scoring",
  "Report generation",
] as const;

/** Which pipeline stages a given template actually performs. */
export function workflowStages(tpl: ScanTemplate): string[] {
  if (tpl.mode === "analysis")
    return [
      "Target selection",
      "Compliance checks",
      "Vulnerability correlation",
      "Risk scoring",
      "Report generation",
    ];
  if (tpl.mode === "agent") return [...SCAN_WORKFLOW];
  const stages = [
    "Target selection",
    "Host discovery",
    "Service detection",
    "Plugin execution",
    "Vulnerability correlation",
    "Risk scoring",
    "Report generation",
  ];
  if (tpl.families.includes("fingerprint")) stages.splice(3, 0, "OS fingerprinting");
  return stages;
}

/** Job contract an external agent receives for an agent-mode template. */
export function agentJobContract(tpl: ScanTemplate, target = "10.0.0.0/24") {
  return {
    job: tpl.agentJob ?? tpl.id,
    template: tpl.id,
    target,
    techniques: tpl.techniques,
    credentials: tpl.credentials ?? [],
    result_endpoint: "/api/public/agent/ingest",
    auth_header: "x-agent-key",
    expected_payload: {
      target,
      agent: "aegis-agent/1.0",
      os: "Ubuntu 22.04",
      ports: [{ port: 445, protocol: "tcp", service: "smb", banner: "Samba 4.15" }],
      findings: [
        {
          plugin_id: `${tpl.id.toUpperCase()}-0001`,
          title: "Example finding title",
          severity: 3,
          cvss: 8.1,
          cve_ids: ["CVE-2017-0144"],
          port: 445,
          service: "smb",
          description: "What the agent observed.",
          solution: "How to fix it.",
          evidence: "Raw protocol evidence.",
        },
      ],
    },
  };
}
