/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAttackGraphRouteImport } from './routes/_authenticated/attack-graph'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFindingsRouteImport } from './routes/_authenticated/findings'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedIntelRouteImport } from './routes/_authenticated/intel'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedScansIndexRouteImport } from './routes/_authenticated/scans/index'
import { Route as AuthenticatedScansScanIdRouteImport } from './routes/_authenticated/scans/$scanId'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates/$templateId'
import { Route as ApiPublicAgentIngestRouteImport } from './routes/api/public/agent/ingest'
import { Route as ApiPublicHooksRunSchedulesRouteImport } from './routes/api/public/hooks/run-schedules'
import { Route as ApiPublicV1AssetsRouteImport } from './routes/api/public/v1/assets'
import { Route as ApiPublicV1FindingsRouteImport } from './routes/api/public/v1/findings'
import { Route as ApiPublicV1OpenapiRouteImport } from './routes/api/public/v1/openapi'
import { Route as ApiPublicV1ScansRouteImport } from './routes/api/public/v1/scans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttackGraphRoute =
  AuthenticatedAttackGraphRouteImport.update({
    id: '/attack-graph',
    path: '/attack-graph',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindingsRoute = AuthenticatedFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelRoute = AuthenticatedIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScansIndexRoute = AuthenticatedScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansScanIdRoute =
  AuthenticatedScansScanIdRouteImport.update({
    id: '/scans/$scanId',
    path: '/scans/$scanId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentIngestRoute = ApiPublicAgentIngestRouteImport.update({
  id: '/api/public/agent/ingest',
  path: '/api/public/agent/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunSchedulesRoute =
  ApiPublicHooksRunSchedulesRouteImport.update({
    id: '/api/public/hooks/run-schedules',
    path: '/api/public/hooks/run-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AssetsRoute = ApiPublicV1AssetsRouteImport.update({
  id: '/api/public/v1/assets',
  path: '/api/public/v1/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FindingsRoute = ApiPublicV1FindingsRouteImport.update({
  id: '/api/public/v1/findings',
  path: '/api/public/v1/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiRoute = ApiPublicV1OpenapiRouteImport.update({
  id: '/api/public/v1/openapi',
  path: '/api/public/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ScansRoute = ApiPublicV1ScansRouteImport.update({
  id: '/api/public/v1/scans',
  path: '/api/public/v1/scans',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attack-graph': typeof AuthenticatedAttackGraphRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/findings': typeof AuthenticatedFindingsRoute
  '/import': typeof AuthenticatedImportRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/intel': typeof AuthenticatedIntelRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/scans/$scanId': typeof AuthenticatedScansScanIdRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/scans/': typeof AuthenticatedScansIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/findings': typeof ApiPublicV1FindingsRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/scans': typeof ApiPublicV1ScansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attack-graph': typeof AuthenticatedAttackGraphRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/findings': typeof AuthenticatedFindingsRoute
  '/import': typeof AuthenticatedImportRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/intel': typeof AuthenticatedIntelRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/scans/$scanId': typeof AuthenticatedScansScanIdRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/scans': typeof AuthenticatedScansIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/findings': typeof ApiPublicV1FindingsRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/scans': typeof ApiPublicV1ScansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/attack-graph': typeof AuthenticatedAttackGraphRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/findings': typeof AuthenticatedFindingsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/intel': typeof AuthenticatedIntelRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/scans/$scanId': typeof AuthenticatedScansScanIdRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/_authenticated/scans/': typeof AuthenticatedScansIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/findings': typeof ApiPublicV1FindingsRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/scans': typeof ApiPublicV1ScansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api-docs'
    | '/assets'
    | '/attack-graph'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/findings'
    | '/import'
    | '/integrations'
    | '/intel'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/scans/$scanId'
    | '/templates/$templateId'
    | '/scans/'
    | '/templates/'
    | '/api/public/agent/ingest'
    | '/api/public/hooks/run-schedules'
    | '/api/public/v1/assets'
    | '/api/public/v1/findings'
    | '/api/public/v1/openapi'
    | '/api/public/v1/scans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api-docs'
    | '/assets'
    | '/attack-graph'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/findings'
    | '/import'
    | '/integrations'
    | '/intel'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/scans/$scanId'
    | '/templates/$templateId'
    | '/scans'
    | '/templates'
    | '/api/public/agent/ingest'
    | '/api/public/hooks/run-schedules'
    | '/api/public/v1/assets'
    | '/api/public/v1/findings'
    | '/api/public/v1/openapi'
    | '/api/public/v1/scans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/api-docs'
    | '/_authenticated/assets'
    | '/_authenticated/attack-graph'
    | '/_authenticated/compliance'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/findings'
    | '/_authenticated/import'
    | '/_authenticated/integrations'
    | '/_authenticated/intel'
    | '/_authenticated/monitoring'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/scans/$scanId'
    | '/_authenticated/templates/$templateId'
    | '/_authenticated/scans/'
    | '/_authenticated/templates/'
    | '/api/public/agent/ingest'
    | '/api/public/hooks/run-schedules'
    | '/api/public/v1/assets'
    | '/api/public/v1/findings'
    | '/api/public/v1/openapi'
    | '/api/public/v1/scans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicAgentIngestRoute: typeof ApiPublicAgentIngestRoute
  ApiPublicHooksRunSchedulesRoute: typeof ApiPublicHooksRunSchedulesRoute
  ApiPublicV1AssetsRoute: typeof ApiPublicV1AssetsRoute
  ApiPublicV1FindingsRoute: typeof ApiPublicV1FindingsRoute
  ApiPublicV1OpenapiRoute: typeof ApiPublicV1OpenapiRoute
  ApiPublicV1ScansRoute: typeof ApiPublicV1ScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attack-graph': {
      id: '/_authenticated/attack-graph'
      path: '/attack-graph'
      fullPath: '/attack-graph'
      preLoaderRoute: typeof AuthenticatedAttackGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/findings': {
      id: '/_authenticated/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof AuthenticatedFindingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intel': {
      id: '/_authenticated/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof AuthenticatedIntelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scans/': {
      id: '/_authenticated/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof AuthenticatedScansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans/$scanId': {
      id: '/_authenticated/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof AuthenticatedScansScanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/ingest': {
      id: '/api/public/agent/ingest'
      path: '/api/public/agent/ingest'
      fullPath: '/api/public/agent/ingest'
      preLoaderRoute: typeof ApiPublicAgentIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-schedules': {
      id: '/api/public/hooks/run-schedules'
      path: '/api/public/hooks/run-schedules'
      fullPath: '/api/public/hooks/run-schedules'
      preLoaderRoute: typeof ApiPublicHooksRunSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/assets': {
      id: '/api/public/v1/assets'
      path: '/api/public/v1/assets'
      fullPath: '/api/public/v1/assets'
      preLoaderRoute: typeof ApiPublicV1AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/findings': {
      id: '/api/public/v1/findings'
      path: '/api/public/v1/findings'
      fullPath: '/api/public/v1/findings'
      preLoaderRoute: typeof ApiPublicV1FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi': {
      id: '/api/public/v1/openapi'
      path: '/api/public/v1/openapi'
      fullPath: '/api/public/v1/openapi'
      preLoaderRoute: typeof ApiPublicV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/scans': {
      id: '/api/public/v1/scans'
      path: '/api/public/v1/scans'
      fullPath: '/api/public/v1/scans'
      preLoaderRoute: typeof ApiPublicV1ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAttackGraphRoute: typeof AuthenticatedAttackGraphRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFindingsRoute: typeof AuthenticatedFindingsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedIntelRoute: typeof AuthenticatedIntelRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedScansScanIdRoute: typeof AuthenticatedScansScanIdRoute
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedScansIndexRoute: typeof AuthenticatedScansIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAttackGraphRoute: AuthenticatedAttackGraphRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFindingsRoute: AuthenticatedFindingsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedIntelRoute: AuthenticatedIntelRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedScansScanIdRoute: AuthenticatedScansScanIdRoute,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedScansIndexRoute: AuthenticatedScansIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicAgentIngestRoute: ApiPublicAgentIngestRoute,
  ApiPublicHooksRunSchedulesRoute: ApiPublicHooksRunSchedulesRoute,
  ApiPublicV1AssetsRoute: ApiPublicV1AssetsRoute,
  ApiPublicV1FindingsRoute: ApiPublicV1FindingsRoute,
  ApiPublicV1OpenapiRoute: ApiPublicV1OpenapiRoute,
  ApiPublicV1ScansRoute: ApiPublicV1ScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
